# Generated by Django 4.2.19 on 2025-07-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='John Doe', max_length=100)),
                ('designation', models.CharField(blank=True, default='Developer', max_length=100)),
                ('company_name', models.CharField(blank=True, default='My Company', max_length=100)),
                ('phone', models.CharField(blank=True, default='+91 0000000000', max_length=20)),
                ('email', models.EmailField(blank=True, default='example@example.com', max_length=254)),
                ('website', models.URLField(blank=True, default='https://www.example.com')),
                ('address', models.TextField(blank=True, default='123, Sample Street, City')),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images/')),
                ('logo', models.ImageField(blank=True, default='company_logos/default.png', upload_to='company_logos/')),
            ],
        ),
    ]
