# Generated by Django 4.2.19 on 2025-07-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingcard',
            name='extra_image',
            field=models.ImageField(blank=True, default='extra_images/default.png', upload_to='extra_images/'),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='facebook_link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='instagram_link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='linkedin_link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='+91 0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='designation',
            field=models.CharField(blank=True, default='Sales Executive', max_length=100),
        ),
    ]
