# Generated by Django 4.2.19 on 2025-07-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_visitingcard_extra_image_visitingcard_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingcard',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
