# Generated by Django 4.2.19 on 2025-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_visitingcard_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingcard',
            name='qr_center_color',
            field=models.CharField(default='#000000', help_text='Hex Color for QR Center', max_length=7),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='qr_edge_color',
            field=models.CharField(default='#0000FF', help_text='Hex Color for QR Edge', max_length=7),
        ),
    ]
