# Generated by Django 4.2.19 on 2025-07-21 10:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_visitingcard_qr_center_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitingcard',
            name='extra_image',
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='qr_center_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='QR Center Color'),
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='qr_edge_color',
            field=colorfield.fields.ColorField(default='#0000FF', image_field=None, max_length=25, samples=None, verbose_name='QR Edge Color'),
        ),
    ]
